// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzi1M2ohcppe0BjMSkSnrlQEYNuHW323U',
    appId: '1:69104439777:web:9c3b406fb8ee283f3102a0',
    messagingSenderId: '69104439777',
    projectId: 'blooddonationapp-60041',
    authDomain: 'blooddonationapp-60041.firebaseapp.com',
    storageBucket: 'blooddonationapp-60041.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0IRC_yTTDVxXn75F975OJTLVGeA3q54',
    appId: '1:69104439777:android:78ef3e35041ad69e3102a0',
    messagingSenderId: '69104439777',
    projectId: 'blooddonationapp-60041',
    storageBucket: 'blooddonationapp-60041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkHDukhWKew9Zm6aP191RapDgDTBgXy6g',
    appId: '1:69104439777:ios:e6e6ea9dfda8b9033102a0',
    messagingSenderId: '69104439777',
    projectId: 'blooddonationapp-60041',
    storageBucket: 'blooddonationapp-60041.appspot.com',
    iosBundleId: 'com.example.bloodBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkHDukhWKew9Zm6aP191RapDgDTBgXy6g',
    appId: '1:69104439777:ios:6393b8e588d676e93102a0',
    messagingSenderId: '69104439777',
    projectId: 'blooddonationapp-60041',
    storageBucket: 'blooddonationapp-60041.appspot.com',
    iosBundleId: 'com.example.bloodBank.RunnerTests',
  );
}
